name: Build and test Shopping App
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v4
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install NPM dependencies
      run: npm install
    - name: Run the unit tests
      run: npm run test:unit
    - name: Display softuni username
      run: echo "ribanec"

  ru-ui-test:
    needs: build_test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v4
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install NPM dependencies
      run: npm install
    - name: install playwright
      run: npx playwright install
    - name: Start application
      run: npm run start &
    - name: Run the UI tests
      run: npm run test:ui


  deploy:
    needs: build_test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.MY_RENDER_SERVICE_ID }}
          api-key: ${{ secrets.MY_RENDER_API_KEY }}
      - name: Wait for deploy
        run: sleep 60

  run-ui-tests:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v3
    - name: Use Node.js18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
    - name: Install project dependencies
      run: npm install
    - name: Install Playwright
      run: npx playwright install
    - name: Run UI tests for the application
      run: npm run test:ui
